provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  blurfilter:
    lang: dockerfile
    handler: ./src/imageFilters/blurfilter
    image: blurfilter:latest
  blackwhitefilter:
    lang: dockerfile
    handler: ./src/imageFilters/blackwhitefilter
    image: blackwhitefilter:latest
  scalefilter:
    lang: dockerfile
    handler: ./src/imageFilters/scalefilter
    image: scalefilter:latest
  circlelayerfilter:
    lang: dockerfile
    handler: ./src/imageFilters/circlelayerfilter
    image: circlelayerfilter:latest
  trianglelayerfilter:
    lang: dockerfile
    handler: ./src/imageFilters/trianglelayerfilter
    image: trianglelayerfilter:latest