provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  blurfilter:
    lang: dockerfile
    handler: ./imageFilters/blurfilter
    image: blurfilter:latest
  blackwhitefilter:
    lang: dockerfile
    handler: ./imageFilters/blackwhitefilter
    image: blackwhitefilter:latest
  scalefilter:
    lang: dockerfile
    handler: ./imageFilters/scalefilter
    image: scalefilter:latest
  circlelayerfilter:
    lang: dockerfile
    handler: ./imageFilters/circlelayerfilter
    image: circlelayerfilter:latest
  trianglelayerfilter:
    lang: dockerfile
    handler: ./imageFilters/trianglelayerfilter
    image: trianglelayerfilter:latest